### ISSUE TITLE
iPad 2 Landscape Not Rendering Correctly

### ISSUE THREAD

**Issue by stevenejb** [asmi1/Realistic#1]
I was messing with the demo and noticed when using an iPad 2 in landscape mode, the menu nav links vanish. The menu drawer also doesn't appear. Both only work when in portrait mode.
Is there a way to fix this easily?
![image](https://cloud.githubusercontent.com/assets/4695267/12548073/7f9b7a1a-c319-11e5-8360-73688a1c0e71.jpeg)

**Comment by asmi1** [comment]
Hi Steven,

A new update (v1.1.7) was submitted to WordPress & Github and I already send you the fix by email. Any way I will post here so anyone can apply it:

Open **style.css** file with any code editor and scroll down until you find this bloc of code:

``` css
@media screen and (min-width:851px) { 
    .mdl-layout__drawer-button {
        display: none;
    }
    .mdl-layout__header-row {
        padding: 0 40px 0 40px;
    }
}
```

Just change **851px** to **1025px** and Save then clear the cache if you are using a cache plugin.

Just that simple! Sorry for any inconvenience :)
